# Generated by Django 3.0.2 on 2020-07-22 15:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='outgoing_friends',
            field=models.ManyToManyField(blank=True, related_name='incoming_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
