# Generated by Django 3.0.2 on 2020-07-23 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_auto_20200628_0814'),
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='leader',
        ),
        migrations.AddField(
            model_name='party',
            name='monster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='monsters.Monster'),
            preserve_default=False,
        ),
    ]
