# Generated by Django 3.0.2 on 2020-07-21 15:25

import battles.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monsters', '0003_auto_20200628_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('state', models.IntegerField(choices=[(0, 'ONGOING'), (1, 'COMPLETED'), (2, 'FORFEITED')], default=battles.utils.BattleState['ONGOING'])),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.Monster')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
