# Generated by Django 3.0.2 on 2020-07-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='datetime_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
