# Generated by Django 3.0.2 on 2020-07-21 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monsters', '0003_auto_20200628_0814'),
        ('battles', '0002_battle_datetime_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='monster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='monsters.Monster'),
        ),
        migrations.AlterField(
            model_name='battle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to=settings.AUTH_USER_MODEL),
        ),
    ]
