# Generated by Django 3.0.2 on 2020-07-25 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battles', '0003_auto_20200721_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='user',
        ),
        migrations.AddField(
            model_name='battle',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='battles', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
