# Generated by Django 3.0.2 on 2020-06-24 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='config',
            new_name='appearance_config',
        ),
        migrations.AddField(
            model_name='character',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='many_characters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
