# Generated by Django 3.0.2 on 2020-06-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_auto_20200624_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
