# Generated by Django 3.0.2 on 2020-07-24 16:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('appearance_config', django.contrib.postgres.fields.jsonb.JSONField()),
                ('equipment_type', models.IntegerField(choices=[(0, 'HELMET'), (1, 'CHEST'), (2, 'SHIELD'), (3, 'WEAPON')])),
                ('equipment_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='equipments.Set')),
            ],
        ),
    ]
