# Generated by Django 3.0.2 on 2020-07-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20200723_0720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recepient_user',
            new_name='receipient_user',
        ),
    ]
