# Generated by Django 3.0.2 on 2020-07-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_auto_20200723_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='receipient_user',
            new_name='recipient_user',
        ),
    ]
