# Generated by Django 3.0.2 on 2020-07-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_auto_20200723_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='chats.Chat'),
        ),
    ]
