# Generated by Django 3.0.2 on 2020-07-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_auto_20200723_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chats.Chat'),
            preserve_default=False,
        ),
    ]
