# Generated by Django 3.0.2 on 2020-06-28 07:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('appearance_config', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
