# Generated by Django 3.0.2 on 2020-07-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0003_auto_20200628_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='monster',
            name='party_size',
            field=models.IntegerField(default=1),
        ),
    ]
