# Generated by Django 3.0.2 on 2020-07-25 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monsters', '0006_monster_drop_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monster',
            name='drop_rate',
        ),
    ]
